language: node

services:
  - docker

stages:
  - name: "release"
    if: branch = master

jobs:
  include:
    - stage: "release"
      name: "release" 
      if: type = push
      env:
        - IMAGE=4s3ti/discort
      before_script:
        - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      install:
        - npm install @semantic-release/github -D
        - npm install @semantic-release/changelog -D
        - npm install @semantic-release-plus/docker -D
      script:
        - docker build -t $IMAGE .
        - npx semantic-release

